const canvas=document.getElementById('whiteboard'),ctx=canvas.getContext('2d'),wrap=document.getElementById('canvasWrap');
const buttons=[...document.querySelectorAll('[data-tool]')],colorInput=document.getElementById('color'),sizeInput=document.getElementById('size'),zoomValue=document.getElementById('zoomValue'),emptyHint=document.getElementById('emptyHint');
const connection=document.getElementById('connection'),presence=document.getElementById('presence'),roomLabel=document.getElementById('roomLabel'),shareBox=document.getElementById('shareBox'),shareLink=document.getElementById('shareLink');
const labels={select:'تحديد',pen:'قلم',eraser:'ممحاة',line:'خط',arrow:'سهم',rectangle:'مستطيل',ellipse:'دائرة',text:'نص'};
let tool='select',drawing=false,start=null,zoom=1,pan={x:0,y:0},grid=false,draft=null;
const params=new URLSearchParams(location.search),room=params.get('room')||location.hash.slice(1)||crypto.randomUUID().slice(0,8);roomLabel.textContent=`جلسة: ${room}`;
const syncUrl=window.WHITEBOARD_SYNC_URL||localStorage.getItem('whiteboardSyncUrl')||'ws://localhost:1234';
const doc=new Y.Doc();const provider=new WebsocketProvider(syncUrl,`science-whiteboard-${room}`,doc);const yObjects=doc.getArray('objects');const undoManager=new Y.UndoManager(yObjects);const awareness=provider.awareness;
const me={name:localStorage.getItem('whiteboardName')||`مستخدم ${Math.floor(Math.random()*90+10)}`,color:['#3c6e71','#d97757','#4a6fa5','#7a9e63','#8a5cd9'][Math.floor(Math.random()*5)]};
awareness.setLocalStateField('user',me);
provider.on('status',e=>{connection.textContent=e.status==='connected'?'متصل الآن':'غير متصل';connection.className=`status ${e.status==='connected'?'online':'offline'}`});
awareness.on('change',renderPresence);function renderPresence(){presence.innerHTML='';[...awareness.getStates().values()].slice(0,8).forEach(s=>{if(!s.user)return;const a=document.createElement('span');a.className='avatar';a.style.background=s.user.color;a.title=s.user.name;a.textContent=(s.user.name||'?').slice(0,1);presence.appendChild(a)})}
function resizeCanvas(){const r=wrap.getBoundingClientRect(),d=window.devicePixelRatio||1;canvas.width=Math.max(1,Math.floor(r.width*d));canvas.height=Math.max(1,Math.floor(r.height*d));canvas.style.width=r.width+'px';canvas.style.height=r.height+'px';ctx.setTransform(d,0,0,d,0,0);render()}window.addEventListener('resize',resizeCanvas);
function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left-pan.x)/zoom,y:(e.clientY-r.top-pan.y)/zoom}}
function style(){return{stroke:colorInput.value,width:Number(sizeInput.value),opacity:1}}
function commit(o){o.id=crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random());yObjects.push([o])}
function drawObject(o){ctx.save();ctx.globalAlpha=o.opacity??1;ctx.strokeStyle=o.stroke||'#17202a';ctx.fillStyle='transparent';ctx.lineWidth=o.width||3;ctx.lineCap='round';ctx.lineJoin='round';if(o.type==='stroke'){ctx.beginPath();o.points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke()}else if(o.type==='line'||o.type==='arrow'){ctx.beginPath();ctx.moveTo(o.x1,o.y1);ctx.lineTo(o.x2,o.y2);ctx.stroke();if(o.type==='arrow'){const a=Math.atan2(o.y2-o.y1,o.x2-o.x1),s=10+o.width;ctx.beginPath();ctx.moveTo(o.x2,o.y2);ctx.lineTo(o.x2-s*Math.cos(a-.5),o.y2-s*Math.sin(a-.5));ctx.moveTo(o.x2,o.y2);ctx.lineTo(o.x2-s*Math.cos(a+.5),o.y2-s*Math.sin(a+.5));ctx.stroke()}}else if(o.type==='rectangle'){ctx.strokeRect(Math.min(o.x,o.x+o.w),Math.min(o.y,o.y+o.h),Math.abs(o.w),Math.abs(o.h))}else if(o.type==='ellipse'){ctx.beginPath();ctx.ellipse(o.x+o.w/2,o.y+o.h/2,Math.abs(o.w/2),Math.abs(o.h/2),0,0,Math.PI*2);ctx.stroke()}else if(o.type==='text'){ctx.fillStyle=o.stroke||'#17202a';ctx.font=`${Math.max(14,o.width*6+10)}px Arial`;ctx.fillText(o.text,o.x,o.y)}ctx.restore()}
function render(){const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);ctx.save();ctx.translate(pan.x,pan.y);ctx.scale(zoom,zoom);if(grid){ctx.save();ctx.strokeStyle='#e7ebef';ctx.lineWidth=1/zoom;const step=25,left=-pan.x/zoom,right=(w-pan.x)/zoom,top=-pan.y/zoom,bottom=(h-pan.y)/zoom;for(let x=Math.floor(left/step)*step;x<right;x+=step){ctx.beginPath();ctx.moveTo(x,top);ctx.lineTo(x,bottom);ctx.stroke()}for(let y=Math.floor(top/step)*step;y<bottom;y+=step){ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(right,y);ctx.stroke()}ctx.restore()}yObjects.toArray().forEach(drawObject);if(draft)drawObject(draft);ctx.restore();emptyHint.classList.toggle('hidden',yObjects.length>0)}
yObjects.observe(render);function setTool(t){tool=t;buttons.forEach(b=>b.classList.toggle('active',b.dataset.tool===t));canvas.style.cursor=t==='select'?'default':'crosshair'}buttons.forEach(b=>b.onclick=()=>setTool(b.dataset.tool));
document.getElementById('undo').onclick=()=>undoManager.undo();document.getElementById('redo').onclick=()=>undoManager.redo();document.getElementById('clear').onclick=()=>{if(yObjects.length)yObjects.delete(0,yObjects.length)};
document.getElementById('gridToggle').onclick=()=>{grid=!grid;document.getElementById('gridToggle').classList.toggle('grid-on',grid);render()};
document.getElementById('zoomIn').onclick=()=>setZoom(zoom+.1);document.getElementById('zoomOut').onclick=()=>setZoom(zoom-.1);document.getElementById('resetView').onclick=()=>{zoom=1;pan={x:0,y:0};updateZoom();render()};function setZoom(v){zoom=Math.max(.5,Math.min(3,v));updateZoom();render()}function updateZoom(){zoomValue.textContent=Math.round(zoom*100)+'%'}
document.getElementById('export').onclick=()=>{const a=document.createElement('a');a.download=`science-whiteboard-${room}.png`;a.href=canvas.toDataURL('image/png');a.click()};
document.getElementById('share').onclick=()=>{shareBox.classList.toggle('open');shareLink.value=`${location.origin}${location.pathname}?room=${encodeURIComponent(room)}`};document.getElementById('copyShare').onclick=async()=>{await navigator.clipboard.writeText(shareLink.value);document.getElementById('copyShare').textContent='تم النسخ ✓';setTimeout(()=>document.getElementById('copyShare').textContent='نسخ الرابط',1200)};
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);start=point(e);drawing=true;draft=null;if(tool==='pen'||tool==='eraser'){const s=style();draft={type:'stroke',points:[start],stroke:tool==='eraser'?'#fff':s.stroke,width:tool==='eraser'?Math.max(12,s.width*4):s.width,opacity:s.opacity}}else if(['line','arrow','rectangle','ellipse'].includes(tool)){const s=style();draft={type:tool,x1:start.x,y1:start.y,x2:start.x,y2:start.y,x:start.x,y:start.y,w:0,h:0,...s}}else if(tool==='text'){const text=prompt('اكتب النص:');if(text)commit({type:'text',x:start.x,y:start.y,text,...style()});drawing=false;render()}});
canvas.addEventListener('pointermove',e=>{if(!drawing)return;const p=point(e);if(draft?.type==='stroke')draft.points.push(p);else if(draft?.type==='line'||draft?.type==='arrow'){draft.x2=p.x;draft.y2=p.y}else if(draft){draft.w=p.x-start.x;draft.h=p.y-start.y}render();awareness.setLocalStateField('cursor',p)});
canvas.addEventListener('pointerup',()=>{if(!drawing)return;drawing=false;if(draft){commit(draft);draft=null;render()}});canvas.addEventListener('pointercancel',()=>{drawing=false;draft=null;render()});
canvas.addEventListener('wheel',e=>{if(e.ctrlKey){e.preventDefault();setZoom(zoom+(e.deltaY<0?.1:-.1))}},{passive:false});
window.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey){if(e.key.toLowerCase()==='z'){e.preventDefault();undoManager.undo()}if(e.key.toLowerCase()==='y'){e.preventDefault();undoManager.redo()}}else if(!e.target.matches('input,textarea')){const k=e.key.toLowerCase();if(k==='v')setTool('select');if(k==='p')setTool('pen');if(k==='e')setTool('eraser')}});
resizeCanvas();renderPresence();setTool('select');
